export const INITIAL_LOAD_EDIT_PROFILE = 'INITIAL_LOAD_EDIT_PROFILE';
export const UPDATE_STAFF_MEMBER_PROFILE = 'UPDATE_STAFF_MEMBER_PROFILE';
// export const ERROR_UPDATE_PERSONAL_DETAILS = 'ERROR_UPDATE_PERSONAL_DETAILS';
