export const INITIAL_LOAD_EDIT_PROFILE = 'INITIAL_LOAD_EDIT_PROFILE';
export const CHANGE_PERSONAL_DETAILS = 'CHANGE_PERSONAL_DETAILS';
export const ERROR_CHANGE_PERSONAL_DETAILS = 'ERROR_CHANGE_PERSONAL_DETAILS';
