/*
export const UPDATE_CONTACT_DETAILS = 'UPDATE_CONTACT_DETAILS';
export const UPDATE_EMPLOYMENT_DETAILS = 'UPDATE_EMPLOYMENT_DETAILS';
export const UPDATE_PERSONAL_DETAILS = 'UPDATE_PERSONAL_DETAILS';
export const API_DATA_STARTED = 'API_DATA_STARTED';
export const API_DATA_SUCCESS = 'API_DATA_SUCCESS';
export const API_DATA_ERROR = 'API_DATA_ERROR';

*/

export const INITIAL_LOAD = 'INITIAL_LOAD';
