export const UPDATE_CONTACT_DETAILS = 'UPDATE_CONTACT_DETAILS';
export const UPDATE_EMPLOYMENT_DETAILS = 'UPDATE_EMPLOYMENT_DETAILS';
export const UPDATE_PERSONAL_DETAILS = 'UPDATE_PERSONAL_DETAILS';




